server:
  Host: "localhost"
  Port: "8080"
  LoggingLevel: "debug"
  ReadTimeout: "15s"
  WriteTimeout: "15s"

postgres:
  PostgreSQLHost: "localhost"
  PostgreSQLPort: "5432"
  PostgreSQLUser: "postgres"
  PostgreSQLPassword: "root"
  PostgreSQLDBName: "cryptogo_db"
  PgDriver: "pgx"

data:
  ETHRecipient: "0xb000c15b40b0da131ceac414ef5a0d73d9e9742e"
  BTCRecipient: ""

tokens:
  Ethplorer: "freekey"