server:
  Host: "localhost"
  Port: "8080"
  LoggingLevel: "debug"
  ReadTimeout: "15s"
  WriteTimeout: "15s"

postgres:
  PostgreSQLHost: "localhost"
  PostgreSQLPort: "5432"
  PostgreSQLUser: "postgres"
  PostgreSQLPassword: "root"
  PostgreSQLDBName: "cryptogo_db"
  PgDriver: "pgx"

addresses:
  BTC: "1DddUC2Cv3C9RcakqoZ2a6FfLjQr9dKVDg"
  ETH: "0xb000c15b40b0da131ceac414ef5a0d73d9e9742e"
  BNB: "0xf426a8d0a94bf039a35cee66dbf0227a7a12d11e"

tokens:
  Ethplorer: "freekey"
  Bscscan: "5SRDNKXNR2QDW3BZN97JDI6C85PPRVYZXG"